Here we will use the TF Agents to train the CartPole environment with DQN.
TF Agents package makes the implementation of RL algo easier.

In [1161]:
import tensorflow as tf
from tf_agents.environments import suite_gym

In [1162]:
env = suite_gym.load("CartPole-v1")

In [1163]:
env

In [1164]:
env.gym

<TimeLimit<OrderEnforcing<CartPoleEnv<CartPole-v1>>>>

In [1165]:
env.reset()

TimeStep(
{'step_type': array(0),
 'reward': array(0., dtype=float32),
 'discount': array(1., dtype=float32),
 'observation': array([-0.04277356,  0.01741097, -0.0390589 , -0.01940242], dtype=float32)})

In [1166]:
env.step(0)

TimeStep(
{'step_type': array(1),
 'reward': array(1., dtype=float32),
 'discount': array(1., dtype=float32),
 'observation': array([-0.04242533, -0.1771297 , -0.03944695,  0.26070562], dtype=float32)})

Explore Environment Specification

In [1167]:
env.observation_spec()

BoundedArraySpec(shape=(4,), dtype=dtype('float32'), name='observation', minimum=[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], maximum=[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38])

In [1168]:
env.action_spec()

BoundedArraySpec(shape=(), dtype=dtype('int64'), name='action', minimum=0, maximum=1)

In [1169]:
env.time_step_spec()

TimeStep(
{'step_type': ArraySpec(shape=(), dtype=dtype('int32'), name='step_type'),
 'reward': ArraySpec(shape=(), dtype=dtype('float32'), name='reward'),
 'discount': BoundedArraySpec(shape=(), dtype=dtype('float32'), name='discount', minimum=0.0, maximum=1.0),
 'observation': BoundedArraySpec(shape=(4,), dtype=dtype('float32'), name='observation', minimum=[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], maximum=[4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38])})

In [1170]:
env.reward_spec()

ArraySpec(shape=(), dtype=dtype('float32'), name='reward')

In [1171]:
env.discount_spec()

BoundedArraySpec(shape=(), dtype=dtype('float32'), name='discount', minimum=0.0, maximum=1.0)

In [1172]:
env.current_time_step()

TimeStep(
{'step_type': array(1),
 'reward': array(1., dtype=float32),
 'discount': array(1., dtype=float32),
 'observation': array([-0.04242533, -0.1771297 , -0.03944695,  0.26070562], dtype=float32)})

Wrap the environment with TFPyEnvironment which supports both py and tf environments.

In [1173]:
from tf_agents.environments.tf_py_environment import TFPyEnvironment

In [1174]:
env = TFPyEnvironment(env)

In [1175]:
env

In [1176]:
env.reset()

TimeStep(
{'step_type': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([0])>,
 'reward': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>,
 'discount': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 'observation': <tf.Tensor: shape=(1, 4), dtype=float32, numpy=
array([[-0.03483076, -0.02679115,  0.01254369, -0.04040315]],
      dtype=float32)>})

In [1177]:
env.step(0)

TimeStep(
{'step_type': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([1])>,
 'reward': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 'discount': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 'observation': <tf.Tensor: shape=(1, 4), dtype=float32, numpy=
array([[-0.03536658, -0.2220907 ,  0.01173563,  0.2562109 ]],
      dtype=float32)>})

In [1178]:
env.observation_spec()

BoundedTensorSpec(shape=(4,), dtype=tf.float32, name='observation', minimum=array([-4.8000002e+00, -3.4028235e+38, -4.1887903e-01, -3.4028235e+38],
      dtype=float32), maximum=array([4.8000002e+00, 3.4028235e+38, 4.1887903e-01, 3.4028235e+38],
      dtype=float32))

In [1179]:
env.action_spec()

BoundedTensorSpec(shape=(), dtype=tf.int64, name='action', minimum=array(0, dtype=int64), maximum=array(1, dtype=int64))

In [1180]:
env.time_step_spec()

TimeStep(
{'step_type': TensorSpec(shape=(), dtype=tf.int32, name='step_type'),
 'reward': TensorSpec(shape=(), dtype=tf.float32, name='reward'),
 'discount': BoundedTensorSpec(shape=(), dtype=tf.float32, name='discount', minimum=array(0., dtype=float32), maximum=array(1., dtype=float32)),
 'observation': BoundedTensorSpec(shape=(4,), dtype=tf.float32, name='observation', minimum=array([-4.8000002e+00, -3.4028235e+38, -4.1887903e-01, -3.4028235e+38],
      dtype=float32), maximum=array([4.8000002e+00, 3.4028235e+38, 4.1887903e-01, 3.4028235e+38],
      dtype=float32))})

In [1181]:
env.reward_spec()

TensorSpec(shape=(), dtype=tf.float32, name='reward')

In [1182]:
env.discount_spec()

BoundedArraySpec(shape=(), dtype=dtype('float32'), name='discount', minimum=0.0, maximum=1.0)

In [1183]:
env.current_time_step()

TimeStep(
{'step_type': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([1])>,
 'reward': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 'discount': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 'observation': <tf.Tensor: shape=(1, 4), dtype=float32, numpy=
array([[-0.03536658, -0.2220907 ,  0.01173563,  0.2562109 ]],
      dtype=float32)>})

Create a Deep Q Network

In [1184]:
from tf_agents.networks.q_network import QNetwork

In [1185]:
help(QNetwork)

Help on class QNetwork in module tf_agents.networks.q_network:

class QNetwork(tf_agents.networks.network.Network)
 |  QNetwork(input_tensor_spec, action_spec, preprocessing_layers=None, preprocessing_combiner=None, conv_layer_params=None, fc_layer_params=(75, 40), dropout_layer_params=None, activation_fn=<function relu at 0x000001A2DD441260>, kernel_initializer=None, batch_squash=True, dtype=tf.float32, q_layer_activation_fn=None, name='QNetwork')
 |  
 |  Feed Forward network.
 |  
 |  Method resolution order:
 |      QNetwork
 |      tf_agents.networks.network.Network
 |      keras.src.engine.base_layer.Layer
 |      tensorflow.python.module.module.Module
 |      tensorflow.python.trackable.autotrackable.AutoTrackable
 |      tensorflow.python.trackable.base.Trackable
 |      keras.src.utils.version_utils.LayerVersionSelector
 |      builtins.object
 |  
 |  Methods defined here:
 |  
 |  __init__(self, input_tensor_spec, action_spec, preprocessing_layers=None, preprocessing_combine

In [1186]:
q_net = QNetwork(env.observation_spec(), env.action_spec())

Create a DQN agent

In [1187]:
from tf_agents.agents.dqn.dqn_agent import DqnAgent
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.losses import MeanSquaredError

In [1188]:
help(DqnAgent)

Help on class DqnAgent in module tf_agents.agents.dqn.dqn_agent:

class DqnAgent(tf_agents.agents.tf_agent.TFAgent)
 |  DqnAgent(time_step_spec: tf_agents.trajectories.time_step.TimeStep, action_spec: Union[tensorflow.python.framework.type_spec.TypeSpec, tensorflow.python.framework.tensor.TensorSpec, tensorflow.python.ops.ragged.ragged_tensor.RaggedTensorSpec, tensorflow.python.framework.sparse_tensor.SparseTensorSpec, ForwardRef('tf_agents.distributions.utils.DistributionSpecV2'), Iterable[ForwardRef('NestedTensorSpec')], Mapping[str, ForwardRef('NestedTensorSpec')]], q_network: tf_agents.networks.network.Network, optimizer: Union[keras.src.optimizers.optimizer.Optimizer, tensorflow.python.training.optimizer.Optimizer], observation_and_action_constraint_splitter: Optional[Callable[[Union[tensorflow.python.framework.type_spec.TypeSpec, tensorflow.python.framework.tensor.TensorSpec, tensorflow.python.ops.ragged.ragged_tensor.RaggedTensorSpec, tensorflow.python.framework.sparse_tensor.Sp

In [1189]:
optimizer = Adam(learning_rate=0.001)
loss = MeanSquaredError('none', 'mean_squared_error')
loss_fn = loss.call
discount_factor = 0.95
epsilon_fn = lambda step: max(1 - step/1600 , 0.01)
target_model_update = 50
train_step = tf.Variable(0)

agent = DqnAgent(
    env.time_step_spec(),
    env.action_spec(),
    q_network=q_net,
    optimizer=optimizer,
    gamma=discount_factor,
    td_errors_loss_fn=loss_fn,
    epsilon_greedy=0.1,
    train_step_counter=train_step,
    target_update_period=target_model_update,
)

In [1190]:
env.time_step_spec()

TimeStep(
{'step_type': TensorSpec(shape=(), dtype=tf.int32, name='step_type'),
 'reward': TensorSpec(shape=(), dtype=tf.float32, name='reward'),
 'discount': BoundedTensorSpec(shape=(), dtype=tf.float32, name='discount', minimum=array(0., dtype=float32), maximum=array(1., dtype=float32)),
 'observation': BoundedTensorSpec(shape=(4,), dtype=tf.float32, name='observation', minimum=array([-4.8000002e+00, -3.4028235e+38, -4.1887903e-01, -3.4028235e+38],
      dtype=float32), maximum=array([4.8000002e+00, 3.4028235e+38, 4.1887903e-01, 3.4028235e+38],
      dtype=float32))})

In [1191]:
agent.initialize()

Create a Replay Buffer to store experiences

In [1192]:
from tf_agents.replay_buffers.tf_uniform_replay_buffer import TFUniformReplayBuffer

In [1193]:
agent.collect_data_spec

Trajectory(
{'step_type': TensorSpec(shape=(), dtype=tf.int32, name='step_type'),
 'observation': BoundedTensorSpec(shape=(4,), dtype=tf.float32, name='observation', minimum=array([-4.8000002e+00, -3.4028235e+38, -4.1887903e-01, -3.4028235e+38],
      dtype=float32), maximum=array([4.8000002e+00, 3.4028235e+38, 4.1887903e-01, 3.4028235e+38],
      dtype=float32)),
 'action': BoundedTensorSpec(shape=(), dtype=tf.int64, name='action', minimum=array(0, dtype=int64), maximum=array(1, dtype=int64)),
 'policy_info': (),
 'next_step_type': TensorSpec(shape=(), dtype=tf.int32, name='step_type'),
 'reward': TensorSpec(shape=(), dtype=tf.float32, name='reward'),
 'discount': BoundedTensorSpec(shape=(), dtype=tf.float32, name='discount', minimum=array(0., dtype=float32), maximum=array(1., dtype=float32))})

In [1251]:
replay_buffer = TFUniformReplayBuffer(
    data_spec= agent.collect_data_spec,
    batch_size= env.batch_size,
    max_length= 10000
)

Create an observer to write into the replay buffer

In [1195]:
replay_buffer_observer = replay_buffer.add_batch

In [1196]:
replay_buffer

In [1197]:
replay_buffer_observer

<bound method ReplayBuffer.add_batch of <tf_agents.replay_buffers.tf_uniform_replay_buffer.TFUniformReplayBuffer object at 0x000001A2E9B0E850>>

Create a Driver that explores environment using a given policy, collects experience and broadcast them to observer.

In [1198]:
from tf_agents.drivers.dynamic_step_driver import DynamicStepDriver

In [1199]:
agent.policy

In [1200]:
collect_driver = DynamicStepDriver(
    env=env,
    policy= agent.collect_policy,
    observers= [replay_buffer_observer],
    num_steps=200
)

Create a driver to just fill the replay buffer with some experiences with a random policy

In [1201]:
from tf_agents.policies.random_tf_policy import RandomTFPolicy

In [1202]:
initial_collect_policy = RandomTFPolicy(env.time_step_spec(), env.action_spec())

In [1203]:
initial_collect_policy

In [1204]:
initial_driver = DynamicStepDriver(
    env,
    initial_collect_policy,
    [replay_buffer_observer],
    num_steps=1000
)

In [1205]:
final_time_step, final_policy_state = initial_driver.run()

In [1206]:
final_time_step

TimeStep(
{'step_type': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([1])>,
 'reward': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 'discount': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
 'observation': <tf.Tensor: shape=(1, 4), dtype=float32, numpy=array([[ 0.06376  ,  0.5485682, -0.081427 , -0.8057638]], dtype=float32)>})

In [1207]:
final_policy_state

()

Create a Dataset of sample a batch of trajectories for agent to train.

In [1208]:
from tf_agents.trajectories.trajectory import to_transition

In [1209]:
trajectories, buffer_info = replay_buffer.get_next(sample_batch_size=2, num_steps=3)

In [1210]:
trajectories

Trajectory(
{'step_type': <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 0],
       [1, 1, 1]])>,
 'observation': <tf.Tensor: shape=(2, 3, 4), dtype=float32, numpy=
array([[[ 0.10607115,  0.38942716, -0.19156896, -1.0095739 ],
        [ 0.11385969,  0.19730616, -0.21176043, -0.78264165],
        [-0.04709382,  0.00837676, -0.01345868,  0.01632897]],

       [[ 0.01289954,  0.0225056 , -0.00814071,  0.00747398],
        [ 0.01334966,  0.21774335, -0.00799123, -0.28776628],
        [ 0.01770452,  0.02273627, -0.01374656,  0.0023856 ]]],
      dtype=float32)>,
 'action': <tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[0, 0, 1],
       [1, 0, 0]], dtype=int64)>,
 'policy_info': (),
 'next_step_type': <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 0, 1],
       [1, 1, 1]])>,
 'reward': <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 0., 1.],
       [1., 1., 1.]], dtype=float32)>,
 'discount': <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0.

In [1211]:
buffer_info

BufferInfo(ids=<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[ 999, 1000, 1001],
       [ 448,  449,  450]], dtype=int64)>, probabilities=<tf.Tensor: shape=(2,), dtype=float32, numpy=array([0.00095877, 0.00095877], dtype=float32)>)

In [1212]:
time_steps, action_steps, next_time_steps = to_transition(trajectories)

In [1213]:
time_steps

TimeStep(
{'step_type': <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [1, 1]])>,
 'reward': <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>,
 'discount': <tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.]], dtype=float32)>,
 'observation': <tf.Tensor: shape=(2, 2, 4), dtype=float32, numpy=
array([[[ 0.10607115,  0.38942716, -0.19156896, -1.0095739 ],
        [ 0.11385969,  0.19730616, -0.21176043, -0.78264165]],

       [[ 0.01289954,  0.0225056 , -0.00814071,  0.00747398],
        [ 0.01334966,  0.21774335, -0.00799123, -0.28776628]]],
      dtype=float32)>})

In [1214]:
action_steps

PolicyStep(action=<tf.Tensor: shape=(2, 2), dtype=int64, numpy=
array([[0, 0],
       [1, 0]], dtype=int64)>, state=(), info=())

In [1233]:
dataset = replay_buffer.as_dataset(
    sample_batch_size=None
)

In [1234]:
dataset

<_MapDataset element_spec=(Trajectory(
{'step_type': TensorSpec(shape=(), dtype=tf.int32, name=None),
 'observation': TensorSpec(shape=(4,), dtype=tf.float32, name=None),
 'action': TensorSpec(shape=(), dtype=tf.int64, name=None),
 'policy_info': (),
 'next_step_type': TensorSpec(shape=(), dtype=tf.int32, name=None),
 'reward': TensorSpec(shape=(), dtype=tf.float32, name=None),
 'discount': TensorSpec(shape=(), dtype=tf.float32, name=None)}), BufferInfo(ids=TensorSpec(shape=(), dtype=tf.int64, name=None), probabilities=TensorSpec(shape=(), dtype=tf.float32, name=None)))>

In [1235]:
it = iter(dataset)

In [1236]:
it

In [1237]:
next(it)

(Trajectory(
 {'step_type': <tf.Tensor: shape=(), dtype=int32, numpy=1>,
  'observation': <tf.Tensor: shape=(4,), dtype=float32, numpy=array([ 0.04498609,  0.6018606 , -0.15551348, -1.0518794 ], dtype=float32)>,
  'action': <tf.Tensor: shape=(), dtype=int64, numpy=0>,
  'policy_info': (),
  'next_step_type': <tf.Tensor: shape=(), dtype=int32, numpy=1>,
  'reward': <tf.Tensor: shape=(), dtype=float32, numpy=1.0>,
  'discount': <tf.Tensor: shape=(), dtype=float32, numpy=1.0>}),
 BufferInfo(ids=<tf.Tensor: shape=(), dtype=int64, numpy=1012>, probabilities=<tf.Tensor: shape=(), dtype=float32, numpy=0.00079176563>))

In [1238]:
next(it)[0]

Trajectory(
{'step_type': <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 'observation': <tf.Tensor: shape=(4,), dtype=float32, numpy=array([-0.06332241, -0.5964989 ,  0.12501273,  0.9641903 ], dtype=float32)>,
 'action': <tf.Tensor: shape=(), dtype=int64, numpy=1>,
 'policy_info': (),
 'next_step_type': <tf.Tensor: shape=(), dtype=int32, numpy=1>,
 'reward': <tf.Tensor: shape=(), dtype=float32, numpy=1.0>,
 'discount': <tf.Tensor: shape=(), dtype=float32, numpy=1.0>})

Create a training loop

In [1239]:
from tf_agents.utils.common import function

In [1240]:
collect_driver.run

In [1241]:
agent.train

In [1242]:
collect_driver.run = function(collect_driver.run)
agent.train = function(agent.train)

In [1243]:
collect_driver.run

In [1244]:
agent.train

In [1245]:
agent.collect_policy.get_initial_state(env.batch_size)

()

In [1246]:
collect_driver.run(None, ())

(TimeStep(
 {'step_type': <tf.Tensor: shape=(1,), dtype=int32, numpy=array([2])>,
  'reward': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([1.], dtype=float32)>,
  'discount': <tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.], dtype=float32)>,
  'observation': <tf.Tensor: shape=(1, 4), dtype=float32, numpy=
 array([[-0.11326218, -1.1524936 ,  0.2179012 ,  2.0201976 ]],
       dtype=float32)>}),
 ())

In [1247]:
train_step

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=0>

In [1248]:
trajectories, buffer_info = next(it)

In [1249]:
agent.train(trajectories)

ValueError: All of the Tensors in `value` must have two outer dimensions. Specifically, tensors must have shape `[B, T] + spec.shape`.
Full shapes of value tensors:
  Trajectory(
{'step_type': TensorShape([]),
 'observation': TensorShape([4]),
 'action': TensorShape([]),
 'policy_info': (),
 'next_step_type': TensorShape([]),
 'reward': TensorShape([]),
 'discount': TensorShape([])}).
Expected shapes (excluding the two outer dimensions):
  Trajectory(
{'step_type': TensorShape([]),
 'observation': TensorShape([4]),
 'action': TensorShape([]),
 'policy_info': (),
 'next_step_type': TensorShape([]),
 'reward': TensorShape([]),
 'discount': TensorShape([])}).